cache:
  directories:
  - $HOME/.m2

language: java

jdk:
  - oraclejdk8

install: mvn install --show-version -DskipTests=true  --errors --batch-mode
#script: mvn test --batch-mode -DskipTests=true
script: mvn test --batch-mode

notifications:
  email:
    recipients:
      - raisercostin@gmail.com
    on_success: always # default: change
    on_failure: always # default: always